name: Latest Medium Blog Post workflow

on:
  schedule: 
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch: 
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Medium posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM-BLOG-POST"
          feed_list: "https://medium.com/@melbdataguy/feed"
          max_post_count: 5
